apiVersion: v1
kind: Service
metadata:
  name: sleuth-zipkin-service
  labels:
    app: sleuth-zipkin-service
spec:
  type: NodePort
  ports:
  - port: 9411
    nodePort: 30003
  selector:
    app: sleuth-zipkin-service
    