spring:  application:    name: currencyservice  zipkin:    enabled: true    base-url: ${zipkin.url:http://localhost:9411}    sleuth:    trace-id128: true    enabled: true    sampler:      probability: 1.0        
server:  port: 8087  


eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      #defaultZone: ${eureka.uri:http://192.168.99.100:8761/eureka}  
      defaultZone: http://localhost:8761/eurekafeign:  hystrix:    enabled: true    management:  endpoints:    web:      exposure:        include: '*'